name: pyenv
channels:
- bioconda
- conda-forge
- defaults

dependencies:
- python=3.7.6*
- snakemake-minimal=6.12.3
- pandas
- geopandas
- geopy
- numpy
- matplotlib
- gdal
- shapely
- openpyxl
- pip

- pip:
  - epiweeks
  - pycountry-convert
  - pycountry
